/* Bot settings 

You don't have to set this if you deploy using heroku because you can simply set them in environment variables, also don't forget to sleep */


const session = process.env.SESSION || 'eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiZUZBRmd6eWJ1TGpnUVNncTlXVWJKaE8yZHliaGdkUG9YdCtQZGR0YzVFYz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiVi9RTzBOWDFWT0ZXVEU1SUhNTXZmdEQzK0c2WHBFQ05MRU9qTFNJNDIwYz0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiI0TGJnMkFNY1NZamZMQ0ZWMTdiemFIdDhPNnAyaWx5U0NsZzd6bkNlQm1zPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJPNVNWdUZGTE1uQ2VSUnJtU2czOGx3NDVlak9nR1BGRDlXdGZEZlkrNndvPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6InVKZWFBdEhjaG1qbXpkQ2pSNUkyMXJUM3VYbXhuY0cvMkZEMXFUalZxMk09In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IjZRQXlaK2lPRzRUZ3I1Um5RMGxSRXdMUC9YanlxazdGcGpNcHV3Y0ZaVWM9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiME9CelpNalp3b05wYm9IeDZQdlZlVnNMMFNDVlU2a1gzcDg4QUc4aktFOD0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiNmQ2Nk1UOFdIVGRNU1BYREg4OWRPOTlUTmRPQnJTdi9YNWdzZlNpUVhqaz0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6ImdTZFYwY0JBT0xKRWdsTHRrVXJxY2ZmRHVwbk9jT0s3L2xaWGF0R1BrcSt5TTVEeTZFTkU4NEEyanBmRXZ3RW5tNmo1bWt2SjlKekhFeU1laS9oQ0NRPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MTUxLCJhZHZTZWNyZXRLZXkiOiIvTUlyR2lMaGlxOFQzSHoySTlMTFc4RnNlektLRkxpbFBhdzgydk5WYUQ4PSIsInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlcyI6W10sIm5leHRQcmVLZXlJZCI6MzIsImZpcnN0VW51cGxvYWRlZFByZUtleUlkIjozMiwiYWNjb3VudFN5bmNDb3VudGVyIjowLCJhY2NvdW50U2V0dGluZ3MiOnsidW5hcmNoaXZlQ2hhdHMiOmZhbHNlfSwiZGV2aWNlSWQiOiJSbU44aDRFZlN6YTNYUWlzbVVjMUF3IiwicGhvbmVJZCI6IjYyZGY2ODE4LTUxYjMtNDAyMy04OTJkLTA3ZWRmN2E4ZGFmYiIsImlkZW50aXR5SWQiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJOZFpMMCt2TlFvQkVXaTNoK1FManpwUWwrazg9In0sInJlZ2lzdGVyZWQiOnRydWUsImJhY2t1cFRva2VuIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiYlBKUTEwUGlzbUlXdW5HKzVNa0FqV0s2R1lJPSJ9LCJyZWdpc3RyYXRpb24iOnt9LCJwYWlyaW5nQ29kZSI6IlNFTVhZRko0IiwibWUiOnsiaWQiOiIyNjM3MTQ3NTc4NTc6NDVAcy53aGF0c2FwcC5uZXQifSwiYWNjb3VudCI6eyJkZXRhaWxzIjoiQ012MW5xRUZFSk9NemJrR0dBRWdBQ2dBIiwiYWNjb3VudFNpZ25hdHVyZUtleSI6Im1jL0tqNzBGanlJcnBsdkVUeEswQStrc3pxLzR4NmQ4MC80ajRmSGVLMkE9IiwiYWNjb3VudFNpZ25hdHVyZSI6IkxKWllUSEpvWDc4RWpKakRWQTY3czh5L3ZoOGdTdHhoSmVjMkFCSkFza2puTlJLUkRWZzJWSWlMWjUyZVVUVUhNTW5nWkJ1YkZWWWlMRjVBUVBpYkNnPT0iLCJkZXZpY2VTaWduYXR1cmUiOiI5QWY4Y3FnaXYzckkrbWFsY3lkbkFjUldvYTNCZHJtaEx0TXI3cTF4KzR6NWM4Rm44ZWhId0VWZm1hYU1xVE5id1lKUUFITjc2MFpyUWR1YkZwR0hEUT09In0sInNpZ25hbElkZW50aXRpZXMiOlt7ImlkZW50aWZpZXIiOnsibmFtZSI6IjI2MzcxNDc1Nzg1Nzo0NUBzLndoYXRzYXBwLm5ldCIsImRldmljZUlkIjowfSwiaWRlbnRpZmllcktleSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkJablB5bys5Qlk4aUs2WmJ4RThTdEFQcExNNnYrTWVuZk5QK0krSHgzaXRnIn19XSwicGxhdGZvcm0iOiJhbmRyb2lkIiwibGFzdEFjY291bnRTeW5jVGltZXN0YW1wIjoxNzMxNDEzNTM2LCJteUFwcFN0YXRlS2V5SWQiOiJBQUFBQUtUQyJ9';

const prefix = process.env.PREFIX || '.';
const mycode = process.env.CODE || "263";
const author = process.env.STICKER_AUTHOR || 'Akio';
const packname = process.env.PACKNAME || 'akio';
const dev = process.env.DEV || '263714757857';
const DevDreaded = dev.split(",");
const botname = process.env.BOTNAME || '𝙰𝙺𝙸𝙾 𝙼𝙳';
const mode = process.env.MODE || 'public';
const gcpresence = process.env.GC_PRESENCE || 'false';
const antionce = process.env.ANTIVIEWONCE || 'true';
const sessionName = "session";
const presence = process.env.WA_PRESENCE || 'online';

const antitag = process.env.ANTITAG || 'true';
const antidelete = process.env.ANTIDELETE || 'true';
const autoview = process.env.AUTOVIEW_STATUS || 'true';
const autolike = process.env.AUTOLIKE_STATUS || 'true';
const autoread = process.env.AUTOREAD || 'true';
const autobio = process.env.AUTOBIO || 'false';

module.exports = {
  sessionName,
  presence,
  autoview,
  autoread,
  botname,
  autobio,
  mode,
  prefix,
  autolike,
  mycode,
  author,
  packname,
  dev,
  DevDreaded,
  gcpresence,
  antionce,
session,
antitag,
antidelete
};
